version: '3.9'

services:
  ceip:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - pgadmin
    networks:
        - ceip

  pg:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - ceip

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9000:80
    depends_on:
      - pg
    env_file:
      - .env
    networks:
      - ceip

networks:
  ceip:
    name: ceip
    driver: bridge
