version: '3.9'

services:
  ceip:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - pgadmin
    networks:
        - ceip

  pg:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - ceip

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 9000:80
    depends_on:
      - pg
    networks:
      - ceip

networks:
  ceip:
    name: ceip
    driver: bridge
