export const ROLES = {
  USER: "Usuário(a) ou Acompanhante",
  EMPLOYEE: "Funcionário(a)",
  VOLUNTEER: "Voluntário(a)"
}

export const REPRESENTATION = {
  USER: "UserOrCompanion",
  EMPLOYEE: "Employee",
  VOLUNTEER: "Volunteer",
}

export const ROLES_REPRESENTATION = {}

ROLES_REPRESENTATION[ROLES.USER] = REPRESENTATION.USER
ROLES_REPRESENTATION[ROLES.EMPLOYEE] = REPRESENTATION.EMPLOYEE
ROLES_REPRESENTATION[ROLES.VOLUNTEER] = REPRESENTATION.VOLUNTEER

export const REV_ROLES_REPRESENTATION = {}

REV_ROLES_REPRESENTATION[REPRESENTATION.USER] = ROLES.USER
REV_ROLES_REPRESENTATION[REPRESENTATION.EMPLOYEE] = ROLES.EMPLOYEE
REV_ROLES_REPRESENTATION[REPRESENTATION.VOLUNTEER] = ROLES.VOLUNTEER

export const ROLES_LIST = Object.values(ROLES)